ocdb12c:
  list:
    -
      url: jdbc:oracle:thin:@localhost:32769:ORCLCDB
      username: sys as sysdba
      password: Oradoc_db1
      driverClass: oracle.jdbc.OracleDriver
    - 
      url: jdbc:oracle:thin:@192.168.83.39:1521/ORCLCDB.localdomain
      username: dummy
      password: dummy
      driver-class: oracle.jdbc.OracleDriver

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:32769:ORCLCDB
    username: sys as sysdba
    password: Oradoc_db1
    
    driver:
      class-name: oracle.jdbc.OracleDriver